FORMAT: 1A
HOST: https://gametask-api.herokuapp.com

# Gametask-backend

GT-API is a simple API allowing front-end to consume data.

## User [/users]

### Fetch Resource [GET]

+ Request 200 (application/json)

        {
        
        }

+ Response 200 (application/json)

        {
            "id": "31097c40-b05c-43fa-b189-07575673a07b",
            "name": "Maria",
            "email": "maria@gmail.com",
            "birthday": "1994-05-15T00:00:00.000Z",
            "gender": "feminino",
            "avatar_url": null,
            "teacher_id": null,
            "student_id": "d5f54ac3-9f53-4507-8d63-33cc3392103a",
            "created_at": "2020-12-03T19:17:18.743Z",
            "updated_at": "2020-12-03T19:18:02.552Z"
        }

### Create Resource [POST]

+ Request 200 (application/json)

        {
            "name": "José",
            "email": "jose@gmail.com",
            "birthday": "02/21/2000",
            "gender": "masculino",
            "avatar_url": "",
            "password": "Jose123456"
        }
        
+ Response 200 (application/json)

        {
            "id": "d1ef430b-7845-4e6e-8444-0c77286c3442",
            "name": "José",
            "email": "jose@gmail.com",
            "birthday": "02/21/2000",
            "gender": "masculino",
            "avatar_url": null,
            "teacher_id": null,
            "student_id": null,
            "created_at": "2020-12-03T17:44:30.503Z",
            "updated_at": "2020-12-03T17:44:30.503Z"
        }
        
### Update Resource [PUT]

+ Request 200 (application/json)

        {
            
        }
        
+ Response 200 (application/json)

        {
            
        }
        
## Sessions [/sessions]

### Create Resource [POST]

+ Request 200 (application/json)

        {
            "email": "jose@gmail.com",
            "password": "Jose123456"
        }

+ Response 200 (application/json)

        {
            "id": "d1ef430b-7845-4e6e-8444-0c77286c3442",
            "name": "José",
            "email": "jose@gmail.com",
            "birthday": "2000-02-21T00:00:00.000Z",
            "gender": "masculino",
            "avatar_url": null,
            "teacher_id": null,
            "student_id": null,
            "created_at": "2020-12-03T17:44:30.503Z",
            "updated_at": "2020-12-03T17:44:30.503Z",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDcwMTc5NzMsImV4cCI6MTYwNzEwNDM3Mywic3ViIjoiZDFlZjQzMGItNzg0NS00ZTZlLTg0NDQtMGM3NzI4NmMzNDQyIn0.dWS7_KgvHmw2QaMWf4y8kEYwmVekiRxDTbkSwP_IfZ0"
        }

## Students [/students]

### Fetch Resource [GET]

+ Request 200 (application/json)

        {
            
        }
        
+ Response 200 (application/json)

        {
            "id": "f78ef9b3-b732-4296-a88c-60f4871ef4da",
            "name": "José",
            "user": {
                "id": "d1ef430b-7845-4e6e-8444-0c77286c3442",
                "name": "José",
                "email": "jose@gmail.com",
                "birthday": "2000-02-21T00:00:00.000Z",
                "gender": "masculino",
                "avatar_url": null,
                "teacher_id": null,
                "student_id": "f78ef9b3-b732-4296-a88c-60f4871ef4da",
                "created_at": "2020-12-03T17:44:30.503Z",
                "updated_at": "2020-12-03T18:44:21.037Z"
            }
        }

### Create Resource [POST]

+ Request 200 (application/json)

        {
            
        }
        
+ Response 200 (application/json)

        {
            "id": "f78ef9b3-b732-4296-a88c-60f4871ef4da",
            "name": "José",
            "user_id": "d1ef430b-7845-4e6e-8444-0c77286c3442"
        }

## Teachers [/teachers]

### Fetch Resource [GET]

+ Request 200 (application/json)

        {
            
        }

+ Response 200 (application/json)

        {
            "id": "653350b6-b49c-4c44-a2a8-7c59765e2189",
            "name": "Felipe",
            "user_id": "e46f341c-8c08-4dfb-b97b-16ef3abd68c8"
        }

### Create Resource [POST]

+ Request 200 (application/json)

        {
            
        }
        
+ Response 200 (application/json)

        {
            "id": "b5cf0060-82e7-4fa3-b182-3f6372911255",
            "name": "João",
            "user_id": "287b41fc-32ec-492e-b90d-9812c176b667"
        }

## Subjects [/subjects]

### Fetch Resource [GET]

+ Request 200 (application/json)

        {
            "name": "Arquitetura de Software",
            "description": "Disciplina do 4 semestre"
        }
        
+ Response 200 (application/json)

        {
            "student_user": [],
            "teacher_user": [
                {
                    "id": "eac392c7-e915-40ff-a635-f07faa67986c",
                    "name": "Arquitetura de Software",
                    "description": "Disciplina do 4 semestre",
                    "background_url": null,
                    "teacher_id": "653350b6-b49c-4c44-a2a8-7c59765e2189",
                    "students": [
                        {
                            "id": "d126780c-f1fb-4492-8b23-5b9c210a2ed8",
                            "name": "Breno Alves",
                            "user_id": "f3b78b1b-9c5f-4830-98ae-8e00ed56c162"
                        },
                        {
                            "id": "d5f54ac3-9f53-4507-8d63-33cc3392103a",
                            "name": "Maria",
                            "user_id": "31097c40-b05c-43fa-b189-07575673a07b"
                        }
                    ],
                    "milestones": [
                        {
                            "id": "3cf6e006-e97e-4d1f-873a-039c71ae51e8",
                            "name": "Padrões de Projeto",
                            "description": "",
                            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c",
                            "blocks": [],
                            "created_at": "2020-12-08T17:31:25.577Z",
                            "updated_at": "2020-12-08T17:31:25.577Z"
                        },
                        {
                            "id": "5f79afd9-5dc9-49d3-9576-d14ff923aa5e",
                            "name": "Primeiro Bimestre",
                            "description": "",
                            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c",
                            "blocks": [
                                {
                                    "id": "097fbc34-f6e4-4731-a2ed-f51112c9fff7",
                                    "name": "Padrões de Projeto",
                                    "milestone_id": "5f79afd9-5dc9-49d3-9576-d14ff923aa5e",
                                    "created_at": "2020-12-08T17:56:40.489Z",
                                    "updated_at": "2020-12-08T17:56:40.489Z"
                                }
                            ],
                            "created_at": "2020-12-08T17:53:09.868Z",
                            "updated_at": "2020-12-08T17:53:09.868Z"
                        }
                    ],
                    "created_at": "2020-12-08T16:28:42.519Z",
                    "updated_at": "2020-12-08T16:28:42.519Z"
                }
            ]
        }

### Create Resource [POST]

+ Request 200 (application/json)

        {
            "name": "Arquitetura de Software",
            "description": "Disciplina do 4 semestre"
        }
        
+ Response 200 (application/json)

        {
            "id": "eac392c7-e915-40ff-a635-f07faa67986c",
            "name": "Arquitetura de Software",
            "description": "Disciplina do 4 semestre",
            "background_url": null,
            "teacher_id": "653350b6-b49c-4c44-a2a8-7c59765e2189",
            "created_at": "2020-12-08T16:28:42.519Z",
            "updated_at": "2020-12-08T16:28:42.519Z"
        }
        
## Subjects/Students/Email [/subjects/student/email]

### Create Resource [POST]

+ Request 200 (application/json)

        {
            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c",
            "student_email": "maria@gmail.com"
        }
        
+ Response 200 (application/json)

        {
            "id": "eac392c7-e915-40ff-a635-f07faa67986c",
            "name": "Arquitetura de Software",
            "description": "Disciplina do 4 semestre",
            "background_url": null,
            "teacher_id": "653350b6-b49c-4c44-a2a8-7c59765e2189",
            "students": [
                {
                    "id": "d126780c-f1fb-4492-8b23-5b9c210a2ed8",
                    "name": "Breno Alves",
                    "user_id": "f3b78b1b-9c5f-4830-98ae-8e00ed56c162"
                },
                {
                    "id": "d5f54ac3-9f53-4507-8d63-33cc3392103a",
                    "name": "Maria",
                    "user_id": "31097c40-b05c-43fa-b189-07575673a07b"
                }
            ],
            "created_at": "2020-12-08T16:28:42.519Z",
            "updated_at": "2020-12-08T16:28:42.519Z"
        }
        
        
## Milestones [/subjects/milestones]
        
### Create Resource [POST]

+ Request 200 (application/json)

        {
            "name": "Primeiro Bimestre", 
            "description": "", 
            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c"
        }
        
+ Response 200 (application/json)

        {
            "id": "5f79afd9-5dc9-49d3-9576-d14ff923aa5e",
            "name": "Primeiro Bimestre",
            "description": "",
            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c",
            "created_at": "2020-12-08T17:53:09.868Z",
            "updated_at": "2020-12-08T17:53:09.868Z"
        }
        
## Blocks [/subjects/blocks]
        
### Create Resource [POST]

+ Request 200 (application/json)

        {
            "name": "Padrões de Projeto", 
            "milestone_id": "5f79afd9-5dc9-49d3-9576-d14ff923aa5e", 
            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c"
        }
        
+ Response 200 (application/json)

        {
            "id": "097fbc34-f6e4-4731-a2ed-f51112c9fff7",
            "name": "Padrões de Projeto",
            "milestone_id": "5f79afd9-5dc9-49d3-9576-d14ff923aa5e",
            "created_at": "2020-12-08T17:56:40.489Z",
            "updated_at": "2020-12-08T17:56:40.489Z"
        }
        
## Task [/subjects/task]

        
### Create Resource [POST]

+ Request 200 (application/json)

        {
            "name": "Seminário de Padrões de Projeto",
            "description": "Elaborar uma videoaula referente às características de um Padrão de projeto sorteado por equipe.",
            "attachment_url": "",
            "due": "12/12/2020",
            "block_id": "097fbc34-f6e4-4731-a2ed-f51112c9fff7",
            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c"
        }
        
+ Response 200 (application/json)

        {
            "id": "12ec7acd-6b27-488d-b70b-d30e1c013b83",
            "name": "Seminário de Padrões de Projeto",
            "description": "Elaborar uma videoaula referente às características de um Padrão de projeto sorteado por equipe.",
            "due": "12/12/2020",
            "attachment_url": "",
            "total_score": 0,
            "block_id": "097fbc34-f6e4-4731-a2ed-f51112c9fff7",
            "created_at": "2020-12-08T18:14:57.563Z",
            "updated_at": "2020-12-08T18:14:57.563Z"
        }
        
## SubjectClass [/subjects/subjectclasses]

### Create Resource [POST]

+ Request 200 (application/json)

        {
            "name": "Padrões de Projeto", 
            "block_id": "097fbc34-f6e4-4731-a2ed-f51112c9fff7", 
            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c", 
            "attachment_url": ""
        }
        
+ Response 200 (application/json)

        {
            "id": "11d3d778-26d1-492a-92c7-9d2af08a992d",
            "name": "Padrões de Projeto",
            "attachment_url": "",
            "block_id": "097fbc34-f6e4-4731-a2ed-f51112c9fff7",
            "subject_id": "eac392c7-e915-40ff-a635-f07faa67986c"
        }